
#  Dockerfile for Node Express Backend api (production)

FROM node:lts-alpine

# Create App Directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app


# Install Dependencies 
COPY package.json yarn*.lock ./
RUN yarn --frozen-lockfile


ARG NODE_ENV=development
ARG APP_PORT

EXPOSE $APP_PORT